fix: Add missing comparator for VulnerabilityAnalysis (#812)
When trying to generate a CycloneDX BOM that has two vulnerabilities
that only differ in their analysis, you get
```
TypeError: '<' not supported between instances of 'VulnerabilityAnalysis' and 'VulnerabilityAnalysis'
```

This PR adds the `__lt__` method for the VulnerabilityAnalysis model to
fix sorting and also includes a test case to verify the fix.

---------

Signed-off-by: Riku Häkli <hakli.riku@gmail.com>
Co-authored-by: Riku Häkli <hakli.riku@gmail.com>